// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaq_oIlSQYaSyFlR_hQ34r3JWq8EHnA_0',
    appId: '1:666434313474:web:d6fcce66b4af44b6f4361b',
    messagingSenderId: '666434313474',
    projectId: 'sixth-form-theatre',
    authDomain: 'sixth-form-theatre.firebaseapp.com',
    storageBucket: 'sixth-form-theatre.appspot.com',
    measurementId: 'G-8XEXCD43DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA9c_S_OcmyvinMHTQy5875RoBiYJEG-U',
    appId: '1:666434313474:android:289d0bb59707e917f4361b',
    messagingSenderId: '666434313474',
    projectId: 'sixth-form-theatre',
    storageBucket: 'sixth-form-theatre.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYZnExhfspjHYvBCXTKbkBpR9hE9FHEFI',
    appId: '1:666434313474:ios:94520ee0440e56cef4361b',
    messagingSenderId: '666434313474',
    projectId: 'sixth-form-theatre',
    storageBucket: 'sixth-form-theatre.appspot.com',
    iosClientId: '666434313474-r5vl12a4sdhg8cfiqm0252kth5aqrltp.apps.googleusercontent.com',
    iosBundleId: 'com.joshualvarez.sixthFormCinemaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYZnExhfspjHYvBCXTKbkBpR9hE9FHEFI',
    appId: '1:666434313474:ios:2ca1759c1962eab8f4361b',
    messagingSenderId: '666434313474',
    projectId: 'sixth-form-theatre',
    storageBucket: 'sixth-form-theatre.appspot.com',
    iosClientId: '666434313474-gf51qiac61m0mpjrosc5hpein04rkakp.apps.googleusercontent.com',
    iosBundleId: 'com.joshualvarez.sixthFormCinemaApp.RunnerTests',
  );
}
